name: Release

on:
  push:
    # branches:
    #   - master
    # NOTE: disabling release action
    # We will be doing manual releases for now, and will fix automatic releases later
    # once we figure out a graceful way to handle pushing commits to protected branches
    branches-ignore:
      - '**'

jobs:
  build:
    # This is temporary, once this project is open sourced, let's change it to Github vm ubuntu
    runs-on: zendesk-stable
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - uses: zendesk/checkout@v2
    - name: Use Node.js
      uses: zendesk/setup-node@v1
      with:
        node-version: '12.x'
    - run: ./scripts/release.sh
      env:
        CI: true
